name: Clean up old GHCR images

on:
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup-old-containers:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Destroy untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'cyrus-docker'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'
